### ISSUE TITLE
单例时只有第一次变灰

### ISSUE THREAD

**Issue by crazecoder** [pinguo-zhouwei/CustomPopwindow#15]
建议设置背景色的方法写在showAsDropDown中

**Comment by crazecoder** [comment]
否则快速点击时，会报错

**Comment by Kotlin2022** [comment]
public JPopWindow showAsDropDown(View anchor, int xOff, int yOff) {
        if (mPopupWindow != null) {
            mPopupWindow.showAsDropDown(anchor, xOff, yOff);
        }
        Activity activity = (Activity) mContentView.getContext();
        if (activity != null && mIsBackgroundDark) {
            //如果设置的值在0 - 1的范围内，则用设置的值，否则用默认值
            final float alpha = (mBackgroundDrakValue > 0 && mBackgroundDrakValue < 1) ? mBackgroundDrakValue : DEFAULT_ALPHA;
            mWindow = activity.getWindow();
            WindowManager.LayoutParams params = mWindow.getAttributes();
            params.alpha = alpha;
            mWindow.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);
            mWindow.setAttributes(params);
        }
        return this;
    }
