### ISSUE TITLE
listview的宽度在资源文件设置无效果,代码里面不设置宽度,,总是显示固定宽度

### ISSUE THREAD

**Issue by Blizzard-liu** [pinguo-zhouwei/CustomPopwindow#5]

**Comment by pinguo-zhouwei** [comment]
没问题啊，如果没设置size，显示的就是布局的大小。布局设置宽高是有效的

**Comment by Blizzard-liu** [comment]
我没有设置size,计算布局的宽度明显不对,自定义布局没问题,listview有问题

**Comment by pinguo-zhouwei** [comment]
ListView 是吧，我用RecyclerView 测试没问题

**Comment by pinguo-zhouwei** [comment]
我去测试了一下ListView ，没问题啊，你说的计算布局宽度明显不对是什么意思呢？是没起作用？还是计算有问题？

**Comment by Blizzard-liu** [comment]
我在布局文件是包裹内容,显示的时候太宽了,我看看你的布局文件

**Comment by Blizzard-liu** [comment]
我刚打断点看了下

   if(mWidth == 0 || mHeight == 0){
            mPopupWindow.getContentView().measure(View.MeasureSpec.UNSPECIFIED, View.MeasureSpec.UNSPECIFIED);
            //如果外面没有设置宽高的情况下，计算宽高并赋值
            mWidth = mPopupWindow.getContentView().getMeasuredWidth();
            mHeight = mPopupWindow.getContentView().getMeasuredHeight();

        }

宽高算的确实对  应该是没刷新

**Comment by Blizzard-liu** [comment]
popupWindow.setWidth(mWidth);
        popupWindow.setHeight(mHeight); 
加这两句就好了
